lcd:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: chinese_chess
    username: root
    password: 123456
  jwt:
    user-secret-key: itlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcditlcd
    user-ttl-hours: 168
    user-token-name: Token
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456